DROP TABLE IF EXISTS PACKAGE_STATE;
CREATE TABLE PACKAGE_STATE (
ID int NOT NULL,
package_state_name VARCHAR(50) NOT NULL,
value VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS SACK_STATE;
CREATE TABLE SACK_STATE (
ID int NOT NULL,
sack_state_name VARCHAR(50) NOT NULL,
value VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS DELIVERY_POINT;
CREATE TABLE DELIVERY_POINT (
ID int NOT NULL,
delivery_point_name VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS SACK_BARCODE;
CREATE TABLE SACK_BARCODE (
ID int NOT NULL,
barcode VARCHAR(50) NOT NULL,
delivery_point  VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS PACKAGE_BARCODE;
CREATE TABLE PACKAGE_BARCODE (
ID int NOT NULL,
barcode VARCHAR(50) NOT NULL,
delivery_point  VARCHAR(20) NOT NULL,
desi  VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS BARCODE_DETAILS;
CREATE TABLE BARCODE_DETAILS (
ID int NOT NULL,
barcode_package VARCHAR(50) NOT NULL,
barcode_sack VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS SHIPMENT_DETAILS;
CREATE TABLE SHIPMENT_DETAILS (
ID int NOT NULL,
barcode VARCHAR(50) NOT NULL,
status VARCHAR(20) NOT NULL
);
